name: Dog API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Install Newman HTML Reporter
        run: npm install -g newman-reporter-htmlextra

      - name: Run Dog API Tests
        env:
          DOG_API_KEY: ${{ secrets.DOG_API_KEY }}
        run: |
          newman run "postman/Dog API Test Suite.postman_collection.json" \
          --environment "postman/Dog API Dev.postman_environment.json" \
          --env-var "dog_api_key=$DOG_API_KEY" \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export results/report.html

      - name: Upload test results
        uses: uses: actions/upload-artifact@v4
        if: always()
        with:
          name: newman-report
          path: results/report.html